package com.bounce;

import java.sql.*;

public class Database {
    private static Connection connection = null;
    private static PreparedStatement preparedStatement = null;

    /* Establishes connection to the MySQL Database */
    public static Connection getConnection() {
        try {
            connection = DriverManager.getConnection("jdbc:mysql://eu-cdbr-west-02.cleardb.net:3306/heroku_45b5e60a7be0064?reconnect=true","b6903f704a649d", "817c7daf");
            return connection;
        } catch (SQLException e) {
            e.printStackTrace();
            return null;
        }
    }

    /* Closes connection to the MySQL Database */
    public static void closeConnection() {
        if (connection != null) {
            try {
                connection.close();
            } catch (SQLException e) {
                e.printStackTrace();
            }
        }
    }

    public static void addToSphereCount(Connection c) {
        try {
            preparedStatement = c.prepareStatement("UPDATE heroku_45b5e60a7be0064.statistics SET `sphere-count` = `sphere-count` + 1;");
            preparedStatement.execute();
        } catch (SQLException e) {
            e.printStackTrace();
        }
    }

    /**
     * Retrieve the amount of spheres generated by all users
     * @return integer stored in DB representing generated spheres
     */
    public static int retrieveSphereCount(Connection c) {
        try {
            preparedStatement = c.prepareStatement("SELECT `sphere-count` FROM statistics");
            ResultSet resultSet = preparedStatement.executeQuery();
            resultSet.next();
            return resultSet.getInt("sphere-count");
        } catch (SQLException e) {
            e.printStackTrace();
            return -1;
        }
    }
}